# Configuración del Backend
backend:
  name: git-gateway
  branch: main 

media_folder: "assets/images/productos"
public_folder: "assets/images/productos"

collections:
  - name: "productos"
    label: "Productos (Joyas)"
    folder: "content/productos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    fields:
      - { label: "Título del Producto", name: "title", widget: "string" }
      - { label: "Precio (sin el signo $)", name: "price", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
      
      - label: "Colección (Baño)"
        name: "section"
        widget: "select"
        options: ["Acero Blanco", "Acero Dorado", "Hombres"]

      # CATEGORÍA MUJER: Solo aparece si eliges Acero Blanco o Dorado
      - label: "Categoría Mujer"
        name: "category_mujer"
        widget: "select"
        options: ["Anillos", "Pulseras", "Collares", "Aritos", "Cintos", "Kids"]
        condition: { field: "section", value: ["Acero Blanco", "Acero Dorado"] }

      # CATEGORÍA HOMBRE: Solo aparece si eliges Hombres
      - label: "Categoría Hombre"
        name: "category_hombre"
        widget: "select"
        options: ["Todo Hombres"]
        condition: { field: "section", value: "Hombres" }
